### ISSUE TITLE
[BQ] What are the most commonly searched spots in the browse view?

### ISSUE THREAD

**Issue by mar-cas3** [ISIS3510-202410-Team23/SwiftApp#163]
@juanyepesp feel free to change the actual question if needed. If you do change it make sure that's updated within the flutter issue too https://github.com/ISIS3510-202410-Team23/FlutterApp/issues/169

**Comment by juanyepesp** [comment]
- This was completed on PR #159, visualization will be done alongside @Alejandro1400
