### ISSUE TITLE
[FEATURE] Implement settings view using local storage (preferences)

### ISSUE THREAD

**Issue by mar-cas3** [ISIS3510-202410-Team23/SwiftApp#164]
- [ ] Feature implementation 
- [ ] Eventual connectivity strategy

**Comment by Laurarestrepo03** [comment]
**Tutorials that might help us:**
- [Toggle switch](https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-a-toggle-switch)
- [Pickers](https://www.hackingwithswift.com/books/ios-swiftui/creating-pickers-in-a-form)

**Comment by Laurarestrepo03** [comment]
Something to take into account: what would happen if the user changes the number of days if the notification was already scheduled? (i.e., in two days they were set to receive a notif, but they changed it to one day). I say we should just have a text below saying "Changes will be reflected once you make a new review or the last scheduled notification is sent"
