### ISSUE TITLE
[FEATURE] Implement user's reviews with cache then network strategy

### ISSUE THREAD

**Issue by mar-cas3** [ISIS3510-202410-Team23/SwiftApp#166]
- [ ] Feature implementation 
- [ ] Eventual connectivity strategy

**Comment by Laurarestrepo03** [comment]
Just so I don't forget: Instgram doesn't allow you to report your own posts, so the report button should only be part of the component if we're in the reviews view. We can do that w/ a boolean, shouldn't be that complicated

**Comment by Laurarestrepo03** [comment]
> Just so I don't forget: Instagram and other social media apps don't allow you to report your own posts, so the report button should only be part of the component if we're in the reviews view. We can do that w/ a boolean, shouldn't be that complicated

And now that I mention it, in the reviews view, should the review show a report button is the review is one's own? 🤔

**Comment by mar-cas3** [comment]
I just saw this, I think maybe what we can do in the ReviewView is to disable the button if the post is made by the user, like it shows but but gray and not clickable.

I can make the change but I'm not sure whether that should a param that we would send to the ReviewCard component we're going to make or if the component itself checks. I would say the former, so the component is only in charge of rendering the review + the reporting and it doesn't have to get the user, that can be done from the parent. 

@Laurarestrepo03 lmk what you think and also if can do the ReviewCard or if you need me to do it!

**Comment by Laurarestrepo03** [comment]
> @Laurarestrepo03 lmk what you think and also if can do the ReviewCard or if you need me to do it!

Okie. I can make the component, no prob, but I'll just wait until the review reporting view is merged (it's already approved btw)

**Comment by mar-cas3** [comment]
Just merged! @Laurarestrepo03

**Comment by Laurarestrepo03** [comment]
> Just merged! @Laurarestrepo03

Thank you @mar-cas3. I was just wondering something tho. You say we should use a param instead of checking in the component iteself but how would that work as a param? 🤔

**Comment by mar-cas3** [comment]
@Laurarestrepo03 , I was thinking that the parent view iterates over the reviews and checks if it belongs to the current user with the getAuthenticatedUser function and that check is what's passed to the component.
