### ISSUE TITLE
[FIX] Security gap: place names instead of gmail

### ISSUE THREAD

**Issue by juanyepesp** [ISIS3510-202410-Team23/SwiftApp#58]

**Comment by mar-cas3** [comment]
@ISIS3510-202410-Team23/swift-team
cc: @ISIS3510-202410-Team23/flutter-team

some things to keep in mind with this issue: 
* the user field in the reviews will probably have to change to a dictionary or something
```
user : {
   name: "Maria"
   email: m.castroi@gmail.com
}
```
* this means that there have to be changes on the backend service to how those reviews are fetched (@juanyepesp & @nklopstock611) and to how the reviews are displayed (@Laurarestrepo03)
* for the backend, i'm guessing it would now have to be by full email but if we add other authentication methods then we might need some ID or something if they don't use an email.
