### ISSUE TITLE
[FU] Save ids of bookmarked spots

### ISSUE THREAD

**Issue by juanyepesp** [ISIS3510-202410-Team23/SwiftApp#86]

**Comment by mar-cas3** [comment]
`systemName` image identifiers:
* `bookmark` 
![image](https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/e6313dad-e869-49ea-8f9b-6f325e33642f)
* `bookmark.fill`
![image](https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/5010f94e-ae19-4c66-ac2f-7b0af3d7cb8a)

**Comment by mar-cas3** [comment]
### @juanyepesp @Laurarestrepo03 here are the options for the bookmark button placement

**Option 1: top & inline with spot title**
<p float="left">
      <img width="300" alt="Screenshot 2024-04-17 at 6 51 54 AM" src="https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/341fc34b-3a0b-43d8-97ab-24e872f2e2e4">
     <img width="300" alt="Screenshot 2024-04-17 at 6 51 34 AM" src="https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/44c870f3-be90-43a0-aee7-8e0e95079b3c">
</p>

**Option 2: middle & inline with spot detail (waiting time, distance)**

<p float="left">
<img width="300" alt="Screenshot 2024-04-17 at 6 52 39 AM" src="https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/ec73efd1-78cf-48b6-a99c-91d5b27ceaab">
<img width="300" alt="Screenshot 2024-04-17 at 6 52 48 AM" src="https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/7bec137b-8db6-4611-bdf8-d410c7ef58c2">
</p>

**Comment by Laurarestrepo03** [comment]
@mar-cas3 I like the first option better :p
